function createfigure(XData1, YData1, YData2)
%CREATEFIGURE(XDATA1, YDATA1, YDATA2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 17-Feb-2017 15:34:05

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039],...
    'OuterPosition',[553 285 576 488]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('ColorOrder',...
    [1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863],...
    'Tag','DisplayAxes1_RealMag');
hold(axes1,'on');

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','FilterSetpoint','Tag','DisplayLine1',...
    'Color',[1 1 0.0666666666666667]);

% Create line
line(XData1,YData2,'DisplayName','Arm Angle','Tag','DisplayLine2',...
    'Color',[0.0745098039215686 0.623529411764706 1]);

% Create xlabel
xlabel(' ');

% Create title
title('Arm Angle','Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-10.206443778816 91.8579940093444]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,...
    'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create text
text('Tag','TimeOffsetStatus','Units','pixels','VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

